### ISSUE TITLE
Module not found: Error: Can't resolve './components/context'

### ISSUE THREAD

**Issue by srinadhbh** [aws-solutions/network-orchestration-for-aws-transit-gateway#101]
ui build is giving the module not found error. 

**Module not found: Error: Can't resolve './components/context' in '/opt/network-orchestration-for-aws-transit-gateway/deployment/regional-s3-assets/ui/src'**

![image](https://github.com/aws-solutions/network-orchestration-for-aws-transit-gateway/assets/88382788/84c37566-ba68-4806-bef7-3468d349f874)

**Comment by srinadhbh** [comment]
Got the same error on V3.3.3 as well. 

![image](https://github.com/aws-solutions/network-orchestration-for-aws-transit-gateway/assets/88382788/3375344e-8094-4cb7-a617-e95fe90e0d97)

**Comment by srinadhbh** [comment]
@groverlalit Any suggestions on how to fix this?

**Comment by groverlalit** [comment]
I am not able to duplicate this issue.  I built it locally and checked in the build pipeline. It finished building with warning. Please see screenshot below. Are you following the steps in README? If not, can you please share steps to duplicate this issue? Thanks for your patience.

<img width="667" alt="Screenshot 2023-10-20 at 4 30 44 PM" src="https://github.com/aws-solutions/network-orchestration-for-aws-transit-gateway/assets/17647720/1d0a73f9-a6da-48de-8d17-6404119fbe0c">

**Comment by srinadhbh** [comment]
Yes. My local environment is Windows, so I launched an AL 2023 EC2 instance and performed the steps as per the Readme file. 

The build should have failed unless you are using a Macbook. As you can see in below screenshot the import statement is "components" whereas the directory is "Components"

![image](https://github.com/aws-solutions/network-orchestration-for-aws-transit-gateway/assets/88382788/5d761045-eb65-449c-9060-1ad3ebb29835)

![image](https://github.com/aws-solutions/network-orchestration-for-aws-transit-gateway/assets/88382788/84b1a875-cce8-45dc-a8a0-9513a4c0fdea)

**Comment by groverlalit** [comment]
Thanks for finding the root cause. Are you able to build it if you change the directory name?

**Comment by groverlalit** [comment]
The directory name has been fixed on the release/v3.3.3 branch. Thanks

**Comment by srinadhbh** [comment]
Thanks. The fix resolved the issue.
