### ISSUE TITLE
Update v2.0.0 to v3.3.3 fails at spoke stack deployment.

### ISSUE THREAD

**Issue by mancinifm** [aws-solutions/network-orchestration-for-aws-transit-gateway#110]
**Describe the bug**

When [updating the spoke stackset to v3.3.3](https://docs.aws.amazon.com/solutions/latest/network-orchestration-aws-transit-gateway/update-the-spoke-stacks.html), all instances complete with:

> Update successful. One or more resources could not be deleted.

CustomServiceLinkedRole	 DELETE_FAILED

Resource of type 'AWS::IAM::ServiceLinkedRole' with identifier 'AWSServiceRoleForVPCTransitGateway' has a conflict. Reason: SLR [AWSServiceRoleForVPCTransitGateway] is in use by other resources: [[RoleUsageType(Region=us-west-2, Resources=[tgw-attach-xxxxxxxxxxxxxxxxx])]].

**To Reproduce**

1. (success) [Update the Hub Stack ](https://docs.aws.amazon.com/solutions/latest/network-orchestration-aws-transit-gateway/update-the-hub-stack.html) to v3.3.3
2. (success) Create the [service-linked role hub stack](https://docs.aws.amazon.com/solutions/latest/network-orchestration-aws-transit-gateway/step-2-launch-the-service-linked-role-hub-stack-optional.html). 
3. (the "bug") [Update the spoke stacks](https://docs.aws.amazon.com/solutions/latest/network-orchestration-aws-transit-gateway/update-the-spoke-stacks.html) to v3.3.3
4. (not attempted) Create the [service-linked role spoke stacks](https://docs.aws.amazon.com/solutions/latest/network-orchestration-aws-transit-gateway/step-4-launch-the-service-linked-role-spoke-stack-optional.html).

**Expected behavior**

For customers where the service linked role was created by the spoke stack in v2.0.0, I can't really see how this update process should succeed. The upgrade tries to delete the role and if you're using the solution and have attachments you can't do this.  But that was how I interpreted the documentation. 

**Resolution**

Fortunately, upgrading the spoke stacks completed successfully and removed the role's Cloudformation resource, leaving the physical resource behind. So for step 4 when deploying the standalone spoke stack, I used cloudformation's [resource import](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-new-stack.html) feature to bring the orhpaned roles back into STNO. You have to modify the template to add a DeletionPolicy and also remove the Outputs section but once you have finished you can update the stacks again with the original templates without issue.

Although I have resolved my own issue I will leave this bug open in case a maintainer wishes to confirm this behavior or offer a better solution for others.

**Please complete the following information about the solution:**

- [x] Version: 2.0.0 -> 3.3.3

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0009) - The AWS CloudFormation template for deployment of the aws-centralized-logging. Version v1.0.0_". You can also find the version from [releases](https://github.com/aws-solutions/aws-centralized-logging/releases)

- [x] Region: [e.g. us-west-2]
- [x] Was the solution modified from the version published on this repository? No
- [-] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs? [How to enable debug mode?](https://docs.aws.amazon.com/solutions/latest/network-orchestration-aws-transit-gateway/troubleshooting.html)

**Screenshots**

N/A

**Additional context**

**Comment by groverlalit** [comment]
Hello @mancinifm,
This is not a bug but expected behavior as you explained caused due to the failure to delete the resource as there is an existing attachment in the region. The reason we didn't implement the deletion policy and instead delete the resource from the CloudFormation stack to avoid this error for new CFN deployments. 
We even tried to use the [CustomSuffix](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-servicelinkedrole.html#cfn-iam-servicelinkedrole-customsuffix) to streamline the experience but TGW SLR does not support custom suffix property yet.

**Comment by groverlalit** [comment]
Duplicate of Issue #96

**Comment by mancinifm** [comment]
Thank you for your response. The linked issue explains the situation so I will close this issue.
