### ISSUE TITLE
STNO Hub Upgrade with Landing Zone 

### ISSUE THREAD

**Issue by nikult** [aws-solutions/network-orchestration-for-aws-transit-gateway#18]
Hello,

IHAC who is trying to upgrade their STNO hub to version 2. They currently use STNO as a core resource in their network account. Sample Manifest below:

core_accounts:
  # Network account
  - name: network
    email: myemail@domain.com
    ssm_parameters:
      - name: /org/member/network/account_id
        value: $[AccountId]
    core_resources:
      - name: STNO-Hub
        template_file: templates/core_accounts/aws-transit-network-orchestrator-hub.template
        parameter_file: parameters/core_accounts/aws-transit-network-orchestrator-hub.json
        deploy_method: stack_set
        regions:
          - us-east-1
          - us-west-2
          - ca-central-1
          - ap-southeast-1
          - eu-central-1
          - eu-west-2
          - ap-southeast-2

The problem is with V2 they want to pass different prefix list IDs and custom CIDRs to the different regions, but landing zone core resources do not allow parameter overrides (like baseline_resources do). The customer is also using a single JSON parameter file.

Any guidance on how to work around or restructure ?

**Comment by rakshb** [comment]
We recommend using the latest version of the solution (V3.2.1). Let us know if you face any issues with the upgrade.
