### ISSUE TITLE
Allow STNO to update the main route table

### ISSUE THREAD

**Issue by kb-tonyj** [aws-solutions/network-orchestration-for-aws-transit-gateway#38]
We have a number of accounts that we connect to a central VPC with STNO. We use the main route table for the spoke accounts, with a default route to our central VPC. STNO should be able to add when accepting the peering request via the console. 

After testing out a number of options, it appears that STNO will not add any routes into the main route table.  We have tested using various DefaultRoute parameters in the stackset: All-Traffic (0/0), RFC-1918, and Custom Destinations (eg. 0.0.0.0/0). STNO will only add the requested route into a custom subnet route table.

Creating and managing a large number of route tables is not a great option to get this working.

A boolean parameter for UpdateDefaultRouteTable in the hub stackset, and associated step logic seems like it should be able to fix this.

There is an older ticket #10  which is the same behaviour that I am seeing. I can confirm that for the subnets we create do not have an existing default route in the main route table.

**Comment by vishwanz** [comment]
+1

**Comment by groverlalit** [comment]
Thanks for the feature request. We have added this to our roadmap.

**Comment by groverlalit** [comment]
The next release will support updating main route table in the VPC. The solution will automatically update main route table if the explicit route table is not associated with the tagged subnet.

**Comment by groverlalit** [comment]
Shipped in v3.3.0 release.
