### ISSUE TITLE
Allow option to mix Principal Types

### ISSUE THREAD

**Issue by jmino** [aws-solutions/network-orchestration-for-aws-transit-gateway#43]
Currently STNO allows only to share with a List of Account IDs or Organization ARN. It would be great to allow for a mixture of both. For example in the case when using the Organization ARN but also wanted to add one account from a different AWS Organizations organization.

**Comment by gsingh04** [comment]
Thanks @jmino for raising the feature request. We have added it to our backlog.

**Comment by rakshb** [comment]
Hello. We reviewed the request; for the specific use case mentioned here, it is not a general best practice to operate a solution across multiple AWS Organizations. So we have decided to keep the current approach (to provide a list of Account IDs or the AWS Organization ARN).
