### ISSUE TITLE
Make web frontend optional

### ISSUE THREAD

**Issue by senorkrabs** [aws-solutions/network-orchestration-for-aws-transit-gateway#49]
**Is your feature request related to a problem? Please describe.**
Some customers do not need the web interface, but the other automation components (i.e. tag-based attachment, association, and propagation) are very valuable. Additionally, several of the services that are used in the web interface aren't supported in GovCloud (CloudFront, AppSync).

**Describe the feature you'd like**
Make the web interface an optional component so that customers that don't require that functionality can opt out of deploying it. This should also help make this solution usable in GovCloud. 

**Additional context**

**Comment by david-prado** [comment]
+1

**Comment by rakshb** [comment]
@senorkrabs Thanks for the request. We have added this in the backlog and will review for a future release.

**Comment by alex-zige** [comment]
+1 agreed.

**Comment by groverlalit** [comment]
We are investigating this feature request. Thanks for opening the issue.

**Comment by groverlalit** [comment]
We have developed this feature. It will be shipped in the next release.
