### ISSUE TITLE
Update route tables for multiple subnets in one availability zone

### ISSUE THREAD

**Issue by kasunsamarakoon** [aws-solutions/network-orchestration-for-aws-transit-gateway#56]
**Is your feature request related to a problem? Please describe.**
We have a 3x3 VPC with 3 subnet tiers across 3 availability zones. e.g. 3 public subnets and 6 private subnets, all using separate route tables. If we tag multiple subnets with "Attach-to-TGW', the solution errors out.

**Describe the feature you'd like**
A method to tag a subnet in each AZ for the transit gateway attachment and another method to tag every subnet that should have its route table updated by the STNO spoke.

**Comment by shujacks** [comment]
Thanks for leaving the comment. We will look into this. What does the error message say specifically?

**Comment by groverlalit** [comment]
In the next release, we plan to support a new tag key that would you the tag subnets in the same AZ and only updates the route table associated with the tagged subnet.
