### ISSUE TITLE
Provide a way to configure other set of default routes to TGW on the spoke subnets

### ISSUE THREAD

**Issue by alFReD-NSH** [aws-solutions/network-orchestration-for-aws-transit-gateway#6]
We would like to configure the default routes to TGW on the spoke subnets to be a set of routes other than All-traffic (0/0), RFC-1918 (10/8, 172.16/12, 192.168/16) and we definitely don't want Configure-Manually.

**Comment by david-prado** [comment]
+1 for this, we are currently adding routes manually because default ones do not fit our needs. We have deployed STNO into multiple regions within Landing Zone solution and need different default routes per region. Having an additional route type that allows customization by region would be ideal.

**Comment by groverlalit** [comment]
Thanks for opening this feature request. We have added this our backlog.

**Comment by alFReD-NSH** [comment]
Actually for us, the ideal would be that the routes added to the spoke subnets would be the propagated routes on the transit gateway route table that they are associated with.

**Comment by alFReD-NSH** [comment]
With the release of shared prefix lists, I would prefer this feature uses those to set up the routes to transit gateway so if propagated routes are updated, then we can simply update the prefix list.

**Comment by groverlalit** [comment]
We release v2.0 yesterday that now supports custom routes, prefix lists to be added to the VPC route tables (associated with tagged subnets).

**Comment by groverlalit** [comment]
> Actually for us, the ideal would be that the routes added to the spoke subnets would be the propagated routes on the transit gateway route table that they are associated with.

@alFReD-NSH This seems to be a new feature request unrelated to the original issue. It would great if you could close this issue and open a new issue with this feature request. Thanks.
