### ISSUE TITLE
VPC RT change

### ISSUE THREAD

**Issue by costi1010** [aws-solutions/network-orchestration-for-aws-transit-gateway#60]
VPC RT modification only works for those subnets which are tagged with "Attach-to-tgw", Though in our case we use a sort of service subnet for the TGW ENI's in order to preserve IP's from our real subnets and we have that subnet associatied with the default RT. The real RT associated with the other subnets do not get changed. If we tag those subnetes with "Attach-to-tgw" then RT gets changed in the subnet RT but we get an error in the STNO saying DuplicateSubnetsinSameZoneError which is obvious as soon we can not create more ENI's for the TGW attachement.
The question and the feature request is: What to do in this particular case to Manipulate changes on the subnet RT in a proper way.

**Comment by groverlalit** [comment]
Thanks for opening this issue. We are investigating this issue.

**Comment by groverlalit** [comment]
In the next release, we plan to support a new tag key that would you the tag subnets in the same AZ and only updates the route table associated with the tagged subnet.
