### ISSUE TITLE
When deleting VPC tags, the STNO does not change association/propagation

### ISSUE THREAD

**Issue by costi1010** [aws-solutions/network-orchestration-for-aws-transit-gateway#61]
When we remove the tags Associated-with and Propagated-to tags and values , STNO does not reflect the change. I would expect that at least the STNO removes the Association and propagation from the TGW RT

**Comment by paul-e-allen** [comment]
Are you sure about this issue? 

I tested a simple deployment and found that when I deleted the `Associated-with` and `Propagated-to` tags from the VPC, STNO updated the TGW Route Table propagation. It left tags on the VPC:
- `STNOStatus-VPCPropagation`: 2022-09-28T14:15:46Z: VPC RT propagation has been disabled from the Transit Gateway Routing Table/Domain
- `STNOStatus-VPCAssociation`: 2022-09-28T14:15:46Z: VPC has been dissociated with the Transit Gateway Routing Table/Domain

You would need to remove the `Attach-to-tgw` tag from the subnet(s) in order for the TGW Attachment(s) to be removed. For me, STNO updated tagging on the subnet:
- `STNOStatus-Subnet`: 2022-09-28T14:14:29Z: Subnet removed from the TGW attachment.

**Comment by tbelmega** [comment]
I can confirm what paul-e-allen already wrote, removing the `Attach-to-tgw` tag from the subnets and then removing `Associate-with` and `Propagate-to` works as expected.

I'm closing the issue. If you're still experiencing problems, please reopen with information about your STNO version number and steps that help us to reproduce the problem.

Best regards,
Thiemo
