### ISSUE TITLE
Removing Subnet from TGW Attachment results in VPC default route being removed

### ISSUE THREAD

**Issue by gfawcett22** [aws-solutions/network-orchestration-for-aws-transit-gateway#73]
**Describe the bug**

If a VPC has multiple subnets attached to the TGW via the `Attach-to-tgw` tag and one of the tags are removed to remove a single subnet, the default route for the VPC is removed even though additional subnets are still attached to the TGW. 

**To Reproduce**

1. Create a VPC with subnets in multiple AZs
2. Attach multiple subnets to the TGW via the `Attach-to-tgw` tag
3. Verify there is a default route of `0.0.0.0/0` in the VPC route table and multiple subnets are attached to the TGW.
4. Remove the `Attach-to-tgw` tag from a single subnet
5. Notice there are still subnet(s) attached to the TGW, but there is no default route in the VPC route table and the subnets attached could not route to the TGW.

**Expected behavior**

Default Route is only removed when all subnets are detached.

**Please complete the following information about the solution:**

- [ v3.1 ] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0009) - The AWS CloudFormation template for deployment of the aws-centralized-logging. Version v1.0.0_". You can also find the version from [releases](https://github.com/aws-solutions/aws-centralized-logging/releases)

- [ us-east-2 ] Region: [e.g. us-east-1]
- [ No ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ Yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ No ] Were there any errors in the CloudWatch Logs? [How to enable debug mode?](https://docs.aws.amazon.com/solutions/latest/serverless-transit-network-orchestrator/troubleshooting.html)

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
The error is being caused [here](https://github.com/aws-solutions/network-orchestration-for-aws-transit-gateway/blob/main/source/lambda/state_machine/lib/handlers/vpc_handler.py#L601) in the vpc_handler. I'm wondering if `self.event.get("Action") == "RemoveSubnet"` should not be there.

**Comment by groverlalit** [comment]
Thanks for opening this issue. We are investigating this issue.
