### ISSUE TITLE
STNO Static Routes Creation in TransitGateway RouteTables

### ISSUE THREAD

**Issue by Palla246** [aws-solutions/network-orchestration-for-aws-transit-gateway#86]
**Is your feature request related to a problem? Please describe.**

when we are doing transit-gateway attachment Propagation in TGW routetables, what ever the secondary cidrs attached to VPC in spoke account are propagated by default. This is causing networking issues in our Landing zone environment. So instead of TGW propagation we want to create static routes with spoke VPC list of primary cidr's and excluding list of secondary cidr's

**Describe the feature you'd like**

we have same secondary CIDR's allocated for each spoke account VPC.   for example spoke VPC cidr's : 10.240.0.0/25, 10.239.0.0/28 and 100.64.0.0/16,100.65.0.0/16, 100.66.0.0/16 , 100.67.0.0/16.

primary cidr's are : 10.240.0.0/25, 10.239.0.0/28 (this will vary for each account with a list two cidr's )
secondary cidr's are : 100.64.0.0/16,100.65.0.0/16, 100.66.0.0/16 , 100.67.0.0/16 (this is same for each spoke account having same cidr's range ) 

i want to create static routes in TGW routetable with spoke vpc primary cidr's list 10.240.0.0/25, 10.239.0.0/28 and exclude list  secondary cidr's list 100.64.0.0/16,100.65.0.0/16, 100.66.0.0/16 , 100.67.0.0/16 in hub account.

**Additional context**

**Comment by trevorndodds** [comment]
Yes, we have this issue too, other than manual mode and rejecting these secondary CIDRs that we do not want to be propagated what other options do we have?

**Comment by morjoan** [comment]
We're currently evaluating this request. Thank you.

**Comment by groverlalit** [comment]
Discussed this with the network SME support the customer directly. This use case can not be supported as TGW service does not support this feature. Currently, TGW service does not support selective propagation. We can either enable or disable propagation for a given TGW-VPC attachment. The service does not provide an option to select specific routes in the VPC route table that can be propagated to the TGW route table.
