### ISSUE TITLE
How to add an Additional Group as Admin

### ISSUE THREAD

**Issue by trevorndodds** [aws-solutions/network-orchestration-for-aws-transit-gateway#88]
We have STNO integrated via Azure AD Group, the group is created in cognito with the users, but I cannot see anyway to grant this Group Admin access. By default its readonly user.  I tried adding the Group to AppSync Schema where AdminGroup was defined but it didn't seem to make any difference. 

I dont want to have to add the users from this group to the AdminGroup, but rather have the group assigned as Admin,

**Comment by awstodd** [comment]
This is not currently possible but we have added this feature to the backlog for review.
