### ISSUE TITLE
Pre-packaged templates returning 403 when viewed

### ISSUE THREAD

**Issue by atownsend247** [aws-solutions/network-orchestration-for-aws-transit-gateway#99]
**Describe the bug**

When trying to access the pre-packaged templates as per the [readme section](https://github.com/aws-solutions/network-orchestration-for-aws-transit-gateway/blob/main/README.md#installing-pre-packaged-solution-template), I'm presented with a 403 access denied request.

**To Reproduce**

Click on the links provided by the readme

**Expected behavior**

The links should load correctly and display the template 

**Please complete the following information about the solution:**

n/a

**Screenshots**

n/a

**Additional context**

**Comment by srinadhbh** [comment]
+1

**Comment by atownsend247** [comment]
This doesn't appear to have been resolved by the latest release yesterday, the template links still appear to go to a 403 page.
